// tutorials/frontend/svelte-apollo/app-final/src/components/Todo/TodoPublicList.svelte
<script>
  import { gql } from "@apollo/client";
  import { onMount } from "svelte";
  import { query, mutation, getClient } from "svelte-apollo";
  import TaskItem from "./TaskItem.svelte";

  export let latestTodo;
  let previousLatestTodo;
  let client = getClient();
  let olderTodosAvailable = latestTodo ? true : false;
  let newTodosCount = 0;
  let initialVariables;

  function getInitialQueryVariables() {
    return { oldestTodoId: latestTodo ? latestTodo.id + 1 : 0 };
  }

  onMount(() => {
    initialVariables = getInitialQueryVariables();
  });

  $: {
    if (previousLatestTodo && previousLatestTodo.id !== latestTodo.id) {
      newTodosCount += 1;
    }
    previousLatestTodo = latestTodo;
  }

  const GET_OLD_PUBLIC_TODOS = gql`
    query getOldPublicTodos($oldestTodoId: Int!) {
      todos(
        where: { is_public: { _eq: true }, id: { _lt: $oldestTodoId } }
        limit: 7
        order_by: { created_at: desc }
      ) {
        id
        title
        created_at
        user {
          name
        }
      }
    }
  `;

  const todos = query(GET_OLD_PUBLIC_TODOS, {
    variables: getInitialQueryVariables(),
  });

  const loadNew = () => {
    const GET_NEW_PUBLIC_TODOS = gql`
      query getNewPublicTodos($latestVisibleId: Int) {
        todos(
          where: { is_public: { _eq: true }, id: { _gt: $latestVisibleId } }
          order_by: { created_at: desc }
        ) {
          id
          title
          created_at
          user {
            name
          }
        }
      }
    `;
    let numTodos = $todos.data && $todos.data.todos && $todos.data.todos.length;
    let newestTodoId = numTodos
      ? $todos.data.todos[0].id
      : latestTodo
      ? latestTodo.id
      : 0;
    todos.fetchMore({
      query: GET_NEW_PUBLIC_TODOS,
      variables: { latestVisibleId: newestTodoId },
      updateQuery: (previousTodos, { fetchMoreResult: { todos } }) => {
        client.writeQuery({
          query: GET_OLD_PUBLIC_TODOS,
          variables: initialVariables,
          data: { todos: [...todos, ...previousTodos.todos] },
        });
        newTodosCount = 0;
      },
    });
  };

  const loadOlder = () => {
    let numTodos = $todos.data && $todos.data.todos && $todos.data.todos.length;
    let oldestTodoId = numTodos
      ? $todos.data.todos[numTodos - 1].id
      : latestTodo
      ? latestTodo.id + 1
      : 0;
    todos.fetchMore({
      query: GET_OLD_PUBLIC_TODOS,
      variables: { oldestTodoId },
      updateQuery: (previousTodos, { fetchMoreResult: { todos } }) => {
        client.writeQuery({
          query: GET_OLD_PUBLIC_TODOS,
          variables: initialVariables,
          data: { todos: [...previousTodos.todos, ...todos] },
        });
      },
    });
  };
</script>

{#if $todos.loading}
  <div>Loading...</div>
{:else if $todos.error}
  <div>Error!</div>
{:else if $todos.data}
  <div class="todoListWrapper">
    {#if newTodosCount > 0}
      <div class="loadMoreSection" on:click={loadNew}>
        New tasks have arrived! ({newTodosCount.toString()})
      </div>
    {/if}

    <ul>
      {#each $todos.data.todos as todo (todo.id)}
        <TaskItem {todo} />
      {/each}
    </ul>

    <div class="loadMoreSection" on:click={loadOlder}>
      {olderTodosAvailable ? "Load older tasks" : "No more public tasks!"}
    </div>
  </div>
{/if}

// tutorials/frontend/react-apollo-hooks/app-boilerplate/src/components/Todo/TodoPublicList.js
import React, { Fragment, useState, useEffect } from "react";
import { useSubscription, useApolloClient, gql } from "@apollo/client";

import TaskItem from "./TaskItem";

const TodoPublicList = props => {
  const [state, setState] = useState({
    olderTodosAvailable: props.latestTodo ? true : false,
    newTodosCount: 0,
    todos: [

    ],
    error: false,
  });

  let numTodos = state.todos.length;
  let oldestTodoId = numTodos
    ? state.todos[numTodos - 1].id
    : props.latestTodo
      ? props.latestTodo.id + 1
      : 0;
  let newestTodoId = numTodos
    ? state.todos[0].id
    : props.latestTodo
      ? props.latestTodo.id
      : 0;
      
  const client = useApolloClient();

  useEffect(() => {
    loadOlder();
  }, []);

  useEffect(
    () => {
      if (props.latestTodo && props.latestTodo.id > newestTodoId) {
        setState(prevState => {
          return { ...prevState, newTodosCount: prevState.newTodosCount + 1 };
        });
        newestTodoId = props.latestTodo.id;
      }
    },
    [props.latestTodo]
  );

  const loadNew = async () => { 
    const GET_NEW_PUBLIC_TODOS = gql`
     query getNewPublicTodos ($latestVisibleId: Int!) {
       todos(where: { is_public: { _eq: true}, id: {_gt: $latestVisibleId}}, order_by: { created_at: desc }) {
         id
         title
         created_at
         user {
           name
         }
       }
     }
   `;
   const { error, data } = await client.query({
      query: GET_NEW_PUBLIC_TODOS,
      variables: {
        latestVisibleId: state.todos.length ? state.todos[0].id : null
      }
    });
 
    if (data) {
      setState(prevState => {
        return {
          ...prevState,
          todos: [...data.todos, ...prevState.todos],
          newTodosCount: 0
        };
      });
      newestTodoId = data.todos[0].id;
    }
    if (error) {
      console.error(error);
      setState(prevState => {
        return { ...prevState, error: true };
      });
    } 
  };

  const loadOlder = async () => {
    const GET_OLD_PUBLIC_TODOS = gql`
      query getOldPublicTodos ($oldestTodoId: Int!) {
        todos (where: { is_public: { _eq: true}, id: {_lt: $oldestTodoId}}, limit: 7, order_by: { created_at: desc }) {
          id
          title
          created_at
          user {
            name
          }
        }
      }`;
   const { error, data } = await client.query({
      query: GET_OLD_PUBLIC_TODOS,
      variables: { oldestTodoId: oldestTodoId }
    });
    if (data.todos.length) {
      setState(prevState => {
        return { ...prevState, todos: [...prevState.todos, ...data.todos] };
      });
      oldestTodoId = data.todos[data.todos.length - 1].id;
    } else {
      setState(prevState => {
        return { ...prevState, olderTodosAvailable: false };
      });
    }
    if (error) {
      console.error(error);
      setState(prevState => {
        return { ...prevState, error: true };
      });
    }
 }

  let todos = state.todos;

  const todoList = (
    <ul>
      {todos.map((todo, index) => {
        return <TaskItem key={index} index={index} todo={todo} />;
      })}
    </ul>
  );

  let newTodosNotification = "";
  if (state.newTodosCount) {
    newTodosNotification = (
      <div className={"loadMoreSection"} onClick={loadNew}>
        New tasks have arrived! ({state.newTodosCount.toString()})
      </div>
    );
  }

  const olderTodosMsg = (
    <div className={"loadMoreSection"} onClick={loadOlder}>
      {state.olderTodosAvailable ? "Load older tasks" : "No more public tasks!"}
    </div>
  );

  return (
    <Fragment>
      <div className="todoListWrapper">
        {newTodosNotification}

        {todoList}

        {olderTodosMsg}
      </div>
    </Fragment>
  );
};

// Run a subscription to get the latest public todo
const NOTIFY_NEW_PUBLIC_TODOS = gql`
subscription notifyNewPublicTodos {
  todos (where: { is_public: { _eq: true}}, limit: 1, order_by: {created_at: desc }) {
    id
    created_at
  }
}
`;


const TodoPublicListSubscription = () => {
  const { loading, error, data } = useSubscription(NOTIFY_NEW_PUBLIC_TODOS);
  if (loading) {
    return <span>Loading...</span>;
  }
  if (error) {
    return <span>Error</span>;
  }
  return (<TodoPublicList latestTodo={data.todos.length ? data.todos[0] : null} />);
};


export default TodoPublicListSubscription;
