// tutorials/frontend/svelte-apollo/app-boilerplate/src/components/Todo/TodoPrivateList.svelte
<script>
  import TodoFilters from "./TodoFilters.svelte";
  import TodoItem from "./TodoItem.svelte";
  let currentFilter = "all";
  let todos = [
    {
      id: "1",
      title: "This is private todo 1",
      is_completed: true,
      is_public: false,
    },
    {
      id: "2",
      title: "This is private todo 2",
      is_completed: false,
      is_public: false,
    },
  ];

  function filterResults(filter) {
    currentFilter = filter;
  }
  function clearCompleted() {}

  function getFilteredTodos(todos, currentFilter) {
    if (currentFilter === "active") {
      return todos.filter((todo) => !todo.is_completed);
    } else if (currentFilter === "completed") {
      return todos.filter((todo) => todo.is_completed);
    }
    return todos;
  }

  $: filteredTodos = getFilteredTodos(todos, currentFilter);
</script>

<div>
  <div class="todoListWrapper">
    <ul>
      {#each filteredTodos as todo (todo.id)}
        <TodoItem {todo} />
      {/each}
    </ul>
  </div>
  <TodoFilters {todos} {currentFilter} {filterResults} {clearCompleted} />
</div>

// tutorials/frontend/rescript-react-apollo/app-boilerplate/src/components/Todo/TodoPrivateList.js
import React, { useState, Fragment } from "react";

import TodoItem from "./TodoItem.bs";
import TodoFilters from "./TodoFilters";

const TodoPrivateList = (props) => {
  const [state, setState] = useState({
    filter: "all",
    clearInProgress: false,
    todos: [
      {
        id: "1",
        title: "This is private todo 1",
        is_completed: true,
        is_public: false,
      },
      {
        id: "2",
        title: "This is private todo 2",
        is_completed: false,
        is_public: false,
      },
    ],
  });

  const filterResults = (filter) => {
    setState({
      ...state,
      filter: filter,
    });
  };

  const clearCompleted = () => {};

  let filteredTodos = state.todos;
  if (state.filter === "active") {
    filteredTodos = state.todos.filter((todo) => todo.is_completed !== true);
  } else if (state.filter === "completed") {
    filteredTodos = state.todos.filter((todo) => todo.is_completed === true);
  }

  const todoList = [];
  filteredTodos.forEach((todo, index) => {
    todoList.push(<TodoItem key={index} index={index} todo={todo} />);
  });

  return (
    <Fragment>
      <div className="todoListWrapper">
        <ul>{todoList}</ul>
      </div>

      <TodoFilters
        todos={filteredTodos}
        currentFilter={state.filter}
        filterResultsFn={filterResults}
        clearCompletedFn={clearCompleted}
        clearInProgress={state.clearInProgress}
      />
    </Fragment>
  );
};

export default TodoPrivateList;
