// tutorials/frontend/typescript-react-apollo/app-final/src/components/Todo/TodoItem.tsx
import * as React from 'react';
import { gql, useMutation } from "@apollo/client";
import { GET_MY_TODOS } from './TodoPrivateList';
import { 
  GetMyTodosQuery,
  RemoveTodoMutationFn,
  Todos,
  ToggleTodoMutation,
  ToggleTodoMutationVariables
} from '../../generated/graphql';

interface TodoItemType {
  index: number,
  todo: Pick<Todos, "id" | "title" | "is_completed">
};

const TOGGLE_TODO = gql`
  mutation toggleTodo ($id: Int!, $isCompleted: Boolean!) {
    update_todos(where: {id: {_eq: $id}}, _set: {is_completed: $isCompleted}) {
      affected_rows
      returning {
        id
        title
        is_completed
      }
    }
  }
`;

const REMOVE_TODO = gql`
  mutation removeTodo ($id: Int!) {
    delete_todos(where: {id: {_eq: $id}}) {
      affected_rows
    }
  }
`;

const TodoItem = ({index, todo}: TodoItemType) => {

  const [todoUpdate] = useMutation<ToggleTodoMutation, ToggleTodoMutationVariables>(
    TOGGLE_TODO, 
    {
      update(cache, { data }) {
        const existingTodos = cache.readQuery<GetMyTodosQuery>({ query: GET_MY_TODOS });
        const newTodos = existingTodos!.todos.map(t => {
          if (t.id === todo.id) {
            return { ...t, ...data!.update_todos!.returning[0] };
          } else {
            return t;
          }
        });
        cache.writeQuery<GetMyTodosQuery>({
          query: GET_MY_TODOS,
          data: {todos: newTodos}
        });
      }
    }
  );

  const [todoRemove] = useMutation<RemoveTodoMutationFn>(
    REMOVE_TODO, 
    {
      update(cache, { data }) {
        const existingTodos = cache.readQuery<GetMyTodosQuery>({ query: GET_MY_TODOS });
        const newTodos = existingTodos!.todos.filter(t => (t.id !== todo.id));
        cache.writeQuery<GetMyTodosQuery>({
          query: GET_MY_TODOS,
          data: {todos: newTodos}
        });
      }
    }
  );

  const removeTodo = (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    todoRemove({
      variables: { id: todo.id },
    });
  };

  const toggleTodo = () => {
    todoUpdate({
      variables: { id: todo.id, isCompleted: !todo.is_completed },
      optimisticResponse: {
        __typename: "mutation_root",
        update_todos: {
          __typename: "todos_mutation_response",
          affected_rows: 1,
          returning: [{
            __typename: "todos",
            id: todo.id,
            title: todo.title,
            is_completed: !todo.is_completed,
          }]
        }
      }
    });
  };

  return (
    <li key={index}>
      <div className="view">
        <div className="round">
          <input
            checked={todo.is_completed}
            type="checkbox"
            id={todo.id!.toString()}
            onChange={() => toggleTodo()}
          />
          <label htmlFor={todo.id!.toString()}/>
        </div>
      </div>

      <div className={"labelContent" + (todo.is_completed ? " completed" : '')}>
        <div>
          {todo.title}
        </div>
      </div>

      <button className="closeBtn" onClick={(e) => removeTodo(e)}>
        x
      </button>
    </li>
  );
};

export default TodoItem;

// tutorials/frontend/svelte-apollo/app-final/src/components/Todo/TodoItem.svelte
<script>
  import { gql } from "@apollo/client";
  import { mutation } from "svelte-apollo";
  import { GET_MY_TODOS } from "./queries";
  export let todo;

  const REMOVE_TODO = gql`
    mutation removeTodo($id: Int!) {
      delete_todos(where: { id: { _eq: $id } }) {
        affected_rows
      }
    }
  `;

  const removeTodoMutation = mutation(REMOVE_TODO);

  const removeTodo = (e) => {
    e.preventDefault();
    e.stopPropagation();
    removeTodoMutation({
      variables: { id: todo.id },
      optimisticResponse: true,
      update: (cache) => {
        const existingTodos = cache.readQuery({ query: GET_MY_TODOS });
        const newTodos = existingTodos.todos.filter((t) => t.id !== todo.id);
        cache.writeQuery({
          query: GET_MY_TODOS,
          data: { todos: newTodos },
        });
      },
    });
  };

  const TOGGLE_TODO = gql`
    mutation toggleTodo($id: Int!, $isCompleted: Boolean!) {
      update_todos(
        where: { id: { _eq: $id } }
        _set: { is_completed: $isCompleted }
      ) {
        affected_rows
      }
    }
  `;

  const toggleTodoMutation = mutation(TOGGLE_TODO);

  const toggleTodo = () => {
    toggleTodoMutation({
      variables: { id: todo.id, isCompleted: !todo.is_completed },
      optimisticResponse: true,
      update: (cache) => {
        const existingTodos = cache.readQuery({ query: GET_MY_TODOS });
        const newTodos = existingTodos.todos.map((t) => {
          if (t.id === todo.id) {
            return { ...t, is_completed: !t.is_completed };
          } else {
            return t;
          }
        });
        cache.writeQuery({
          query: GET_MY_TODOS,
          data: { todos: newTodos },
        });
      },
    });
  };
</script>

<li>
  <div class="view">
    <div class="round">
      <input
        checked={todo.is_completed}
        type="checkbox"
        id={todo.id}
        on:change={toggleTodo}
      />
      <label for={todo.id} />
    </div>
  </div>

  <div class={"labelContent" + (todo.is_completed ? " completed" : "")}>
    <div>{todo.title}</div>
  </div>

  <button class="closeBtn" on:click={removeTodo}> x </button>
</li>
