// tutorials/frontend/rescript-react-apollo/app-final/src/components/Todo/TodoPublicWrapper.js
import React from "react";

import TodoInput from "./TodoInput.bs";
import TodoPublicList from "./TodoPublicList";

const TodoPublicWrapper = () => {
  return (
    <div className="todoWrapper">
      <div className="sectionHeader">Public feed (realtime)</div>

      <TodoInput isPublic />
      <TodoPublicList />
    </div>
  );
};

export default TodoPublicWrapper;

// tutorials/frontend/svelte-apollo/app-final/src/components/Todo/TodoPublicWrapper.svelte
<script>
  import TodoInput from "./TodoInput.svelte";
  import TodoPublicListSubscription from "./TodoPublicListSubscription.svelte";
</script>

<div class="todoWrapper">
  <div class="sectionHeader">Public feed (realtime)</div>
  <TodoInput isPublic={true} />
  <TodoPublicListSubscription />
</div>
