// tutorials/frontend/angular-apollo/app-boilerplate/src/app/Todo/TodoFilters.ts
import { Component, Input, Output, EventEmitter, OnChanges } from '@angular/core';

@Component({
  selector: 'TodoFilters',
  templateUrl: './TodoFilters.template.html',
})

export class TodoFilters implements OnChanges {
  @Input() todos: any;
  @Input() currentFilter: any;
  @Output() filterResultsFn: EventEmitter<any> = new EventEmitter();
  @Output() clearCompletedFn: EventEmitter<any> = new EventEmitter();

  itemCount: any;

  ngOnChanges() {
    this.updateItemCount();
  }

  updateItemCount() {
    this.itemCount = this.todos.length;
    const activeTodos = this.todos.filter(todo => todo.is_completed !== true);

    if (this.currentFilter === 'active') {
      this.itemCount = activeTodos.length;
    } else if (this.currentFilter === 'completed') {
      this.itemCount = this.todos.length - activeTodos.length;
    }
  }

  clearCompletedFnWrapper(item: any) {
    this.clearCompletedFn.emit(item);
  }

  filterResultsHandler(filter) {
    this.filterResultsFn.emit({ event: event, filter: filter });
  };
}

// tutorials/frontend/svelte-apollo/app-final/src/components/Todo/TodoFilters.svelte
<script>
  export let todos;
  export let currentFilter;
  export let filterResults;
  export let clearCompleted;

  const filterResultsHandler = (filter) => {
    return () => {
      filterResults(filter);
    };
  };

  $: activeTodos = todos.filter((todo) => todo.is_completed !== true);

  $: itemCount =
    currentFilter === "active"
      ? activeTodos.length
      : currentFilter === "completed"
      ? todos.length - activeTodos.length
      : todos.length;
</script>

<div class="footerList">
  <span>
    {" "}
    {itemCount}
    {itemCount !== 1 ? "items" : "item"}
  </span>

  <ul>
    <li on:click={filterResultsHandler("all")}>
      <a class={currentFilter === "all" ? "selected" : ""}>All</a>
    </li>

    <li on:click={filterResultsHandler("active")}>
      <a class={currentFilter === "active" ? "selected" : ""}>Active</a>
    </li>

    <li on:click={filterResultsHandler("completed")}>
      <a class={currentFilter === "completed" ? "selected" : ""}> Completed </a>
    </li>
  </ul>

  <button onClick={clearCompleted} class="clearComp"> Clear completed </button>
</div>
