// tutorials/frontend/react-apollo-hooks/app-boilerplate/src/components/Todo/TodoPrivateList.js
import React, { useState, Fragment } from "react";
import { useQuery, useMutation, gql } from "@apollo/client";

import TodoItem from "./TodoItem";
import TodoFilters from "./TodoFilters";

const GET_MY_TODOS = gql`
  query getMyTodos {
    todos(where: { is_public: { _eq: false} }, order_by: { created_at: desc }) {
      id
      title
      created_at
      is_completed
  }
 }`;

const CLEAR_COMPLETED = gql`
mutation clearCompleted {
  delete_todos(where: {is_completed: {_eq: true}, is_public: {_eq: false}}) {
    affected_rows
  }
}
`;

const TodoPrivateList = props => {
  const [state, setState] = useState({
    filter: "all",
    clearInProgress: false,
  });

  const filterResults = filter => {
    setState({
      ...state,
      filter: filter
    });
  };

  const [clearCompletedTodos] = useMutation(CLEAR_COMPLETED);

  const clearCompleted = () => {
    clearCompletedTodos({
      optimisticResponse: true,
      update: (cache, { data }) => {
        const existingTodos = cache.readQuery({ query: GET_MY_TODOS });
        const newTodos = existingTodos.todos.filter(t => (!t.is_completed));
        cache.writeQuery({ query: GET_MY_TODOS, data: { todos: newTodos } });
      }
    });
  };

  const { todos } = props;
  let filteredTodos = todos;
  if (state.filter === "active") {
    filteredTodos = todos.filter(todo => todo.is_completed !== true);
  } else if (state.filter === "completed") {
    filteredTodos = todos.filter(todo => todo.is_completed === true);
  }

  const todoList = [];
  filteredTodos.forEach((todo, index) => {
    todoList.push(<TodoItem key={index} index={index} todo={todo} />);
  });

  return (
    <Fragment>
      <div className="todoListWrapper">
        <ul>{todoList}</ul>
      </div>

      <TodoFilters
        todos={filteredTodos}
        currentFilter={state.filter}
        filterResultsFn={filterResults}
        clearCompletedFn={clearCompleted}
        clearInProgress={state.clearInProgress}
      />
    </Fragment>
  );
};


const TodoPrivateListQuery = () => {
  const { loading, error, data } = useQuery(GET_MY_TODOS);

  if (loading) {
    return <div>Loading...</div>;
  }
  if (error) {
    console.error(error);
    return <div>Error!</div>;
  }
  return <TodoPrivateList todos={data.todos} />;
};

export default TodoPrivateListQuery;
export { GET_MY_TODOS };

// tutorials/frontend/svelte-apollo/app-final/src/components/Todo/TodoPrivateList.svelte
<script>
  import { gql } from "@apollo/client";
  import { query, mutation } from "svelte-apollo";
  import TodoFilters from "./TodoFilters.svelte";
  import TodoItem from "./TodoItem.svelte";
  import { GET_MY_TODOS } from "./queries";
  let currentFilter = "all";

  const todos = query(GET_MY_TODOS);

  function filterResults(filter) {
    currentFilter = filter;
  }

  function getFilteredTodos(todos, currentFilter) {
    if (currentFilter === "active") {
      return todos.filter((todo) => !todo.is_completed);
    } else if (currentFilter === "completed") {
      return todos.filter((todo) => todo.is_completed);
    }
    return todos;
  }

  $: filteredTodos = $todos.data
    ? getFilteredTodos($todos.data.todos, currentFilter)
    : [];

  const CLEAR_COMPLETED = gql`
    mutation clearCompleted {
      delete_todos(
        where: { is_completed: { _eq: true }, is_public: { _eq: false } }
      ) {
        affected_rows
      }
    }
  `;

  const clearCompletedTodos = mutation(CLEAR_COMPLETED);

  const clearCompleted = () => {
    clearCompletedTodos({
      optimisticResponse: true,
      update: (cache, { data }) => {
        const existingTodos = cache.readQuery({ query: GET_MY_TODOS });
        const newTodos = existingTodos.todos.filter((t) => !t.is_completed);
        cache.writeQuery({ query: GET_MY_TODOS, data: { todos: newTodos } });
      },
    });
  };
</script>

{#if $todos.loading}
  <div>Loading...</div>
{:else if $todos.error}
  <div>Error!</div>
{:else if $todos.data}
  <div>
    <div class="todoListWrapper">
      <ul>
        {#each filteredTodos as todo (todo.id)}
          <TodoItem {todo} />
        {/each}
      </ul>
    </div>
    <TodoFilters
      todos={$todos.data.todos}
      {currentFilter}
      {filterResults}
      {clearCompleted}
    />
  </div>
{/if}
