// tutorials/frontend/react-apollo-hooks/app-final/src/components/Todo/TodoPublicList.js
import React, { Fragment, useState, useEffect } from "react";
import { useSubscription, useApolloClient, gql } from "@apollo/client";
import TaskItem from "./TaskItem";

const TodoPublicList = props => {
  const [state, setState] = useState({
    olderTodosAvailable: props.latestTodo ? true : false,
    newTodosCount: 0,
    error: false,
    todos: []
  });

  let numTodos = state.todos.length;
  let oldestTodoId = numTodos
    ? state.todos[numTodos - 1].id
    : props.latestTodo
      ? props.latestTodo.id + 1
      : 0;
  let newestTodoId = numTodos
    ? state.todos[0].id
    : props.latestTodo
      ? props.latestTodo.id
      : 0;

  const client = useApolloClient();

  useEffect(() => {
    loadOlder();
  }, []);

  useEffect(
    () => {
      if (props.latestTodo && props.latestTodo.id > newestTodoId) {
        setState(prevState => {
          return { ...prevState, newTodosCount: prevState.newTodosCount + 1 };
        });
        newestTodoId = props.latestTodo.id;
      }
    },
    [props.latestTodo]
  );

  const loadOlder = async () => {
    const GET_OLD_PUBLIC_TODOS = gql`
      query getOldPublicTodos($oldestTodoId: Int!) {
        todos(
          where: { is_public: { _eq: true }, id: { _lt: $oldestTodoId } }
          limit: 7
          order_by: { created_at: desc }
        ) {
          id
          title
          created_at
          user {
            name
          }
        }
      }
    `;

    const { error, data } = await client.query({
      query: GET_OLD_PUBLIC_TODOS,
      variables: { oldestTodoId: oldestTodoId }
    });

    if (data.todos.length) {
      setState(prevState => {
        return { ...prevState, todos: [...prevState.todos, ...data.todos] };
      });
      oldestTodoId = data.todos[data.todos.length - 1].id;
    } else {
      setState(prevState => {
        return { ...prevState, olderTodosAvailable: false };
      });
    }
    if (error) {
      console.error(error);
      setState(prevState => {
        return { ...prevState, error: true };
      });
    }
  };

  const loadNew = async () => {
    const GET_NEW_PUBLIC_TODOS = gql`
      query getNewPublicTodos($latestVisibleId: Int) {
        todos(
          where: { is_public: { _eq: true }, id: { _gt: $latestVisibleId } }
          order_by: { created_at: desc }
        ) {
          id
          title
          created_at
          user {
            name
          }
        }
      }
    `;

    const { error, data } = await client.query({
      query: GET_NEW_PUBLIC_TODOS,
      variables: {
        latestVisibleId: state.todos.length ? state.todos[0].id : null
      }
    });

    if (data) {
      setState(prevState => {
        return {
          ...prevState,
          todos: [...data.todos, ...prevState.todos],
          newTodosCount: 0
        };
      });
      newestTodoId = data.todos[0].id;
    }
    if (error) {
      console.error(error);
      setState(prevState => {
        return { ...prevState, error: true };
      });
    }
  };

  return (
    <Fragment>
      <div className="todoListWrapper">
        {state.newTodosCount !== 0 && (
          <div className={"loadMoreSection"} onClick={loadNew}>
            New tasks have arrived! ({state.newTodosCount.toString()})
          </div>
        )}

        <ul>
          {state.todos &&
            state.todos.map((todo, index) => {
              return <TaskItem key={index} index={index} todo={todo} />;
            })}
        </ul>

        <div className={"loadMoreSection"} onClick={loadOlder}>
          {state.olderTodosAvailable
            ? "Load older tasks"
            : "No more public tasks!"}
        </div>
      </div>
    </Fragment>
  );
};

// Run a subscription to get the latest public todo
const NOTIFY_NEW_PUBLIC_TODOS = gql`
  subscription notifyNewPublicTodos {
    todos(
      where: { is_public: { _eq: true } }
      limit: 1
      order_by: { created_at: desc }
    ) {
      id
      created_at
    }
  }
`;

const TodoPublicListSubscription = () => {
  const { loading, error, data } = useSubscription(NOTIFY_NEW_PUBLIC_TODOS);
  if (loading) {
    return <span>Loading...</span>;
  }
  if (error) {
    return <span>Error</span>;
  }
  return (
    <TodoPublicList latestTodo={data.todos.length ? data.todos[0] : null} />
  );
};
export default TodoPublicListSubscription;

// tutorials/frontend/angular-apollo/app-final/src/app/Todo/TodoPublicList.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Subscription } from 'rxjs';
import { Apollo } from 'apollo-angular';
import gql from 'graphql-tag';

// Run a subscription to get the latest public todo
const NOTIFY_NEW_PUBLIC_TODOS = gql`
  subscription notifyNewPublicTodos {
    todos(
      where: { is_public: { _eq: true } }
      limit: 1
      order_by: { created_at: desc }
    ) {
      id
      created_at
    }
  }
`;

@Component({
  selector: 'TodoPublicList',
  templateUrl: './TodoPublicList.template.html',
})
export class TodoPublicList implements OnInit, OnDestroy {
  olderTodosAvailable = true;
  newTodosCount = 0;
  oldestTodoId;
  newestTodoId;
  todos = [];
  loading = true;

  private oldTodosQuerySubscription: Subscription;
  private newTodosQuerySubscription: Subscription;
  private notifyNewTodosQuerySubscription: Subscription;

  constructor(private apollo: Apollo) {}

  ngOnInit() {
    this.getNotifications();
  }

  getNotifications() {
    this.notifyNewTodosQuerySubscription = this.apollo
      .subscribe({
        query: NOTIFY_NEW_PUBLIC_TODOS,
      })
      .subscribe(
        ({ data, loading }) => {
          this.loading = loading;
          if (data) {
            const latestTodo = data.todos.length ? data.todos[0] : null;
            this.olderTodosAvailable = latestTodo ? true : false;
            this.oldestTodoId = latestTodo ? latestTodo.id + 1 : 0;
            if (latestTodo && latestTodo.id > this.newestTodoId) {
              this.newestTodoId = latestTodo.id;
              this.newTodosCount = this.newTodosCount + 1;
            } else {
              this.newestTodoId = latestTodo ? latestTodo.id : 0;
              this.loadOlder();
            }
          }
          console.log('got data ', data);
        },
        (error) => {
          console.log('there was an error sending the query', error);
        }
      );
  }

  loadNew() {
    const GET_NEW_PUBLIC_TODOS = gql`
      query getNewPublicTodos($latestVisibleId: Int!) {
        todos(
          where: { is_public: { _eq: true }, id: { _gt: $latestVisibleId } }
          order_by: { created_at: desc }
        ) {
          id
          title
          created_at
          user {
            name
          }
        }
      }
    `;
    this.newTodosQuerySubscription = this.apollo
      .watchQuery({
        query: GET_NEW_PUBLIC_TODOS,
        variables: { latestVisibleId: this.todos[0].id },
      })
      .valueChanges.subscribe(
        ({ data, loading }) => {
          const todosData: any = data;
          if (todosData) {
            this.newestTodoId = todosData.todos[0].id;
            this.todos = [...todosData.todos, ...this.todos];
            this.newTodosCount = 0;
          }
          console.log('got data ', data);
        },
        (error) => {
          console.log('there was an error sending the query', error);
        }
      );
  }

  loadOlder() {
    const GET_OLD_PUBLIC_TODOS = gql`
      query getOldPublicTodos($oldestTodoId: Int!) {
        todos(
          where: { is_public: { _eq: true }, id: { _lt: $oldestTodoId } }
          limit: 7
          order_by: { created_at: desc }
        ) {
          id
          title
          created_at
          user {
            name
          }
        }
      }
    `;
    this.oldTodosQuerySubscription = this.apollo
      .watchQuery({
        query: GET_OLD_PUBLIC_TODOS,
        variables: { oldestTodoId: this.oldestTodoId },
      })
      .valueChanges.subscribe(
        ({ data, loading }) => {
          const todosData: any = data;
          if (todosData) {
            if (todosData.todos.length) {
              this.oldestTodoId =
                todosData.todos[todosData.todos.length - 1].id;
              this.todos = [...this.todos, ...todosData.todos];
            } else {
              this.olderTodosAvailable = false;
            }
          }
          console.log('got data ', data);
        },
        (error) => {
          console.log('there was an error sending the query', error);
        }
      );
  }

  ngOnDestroy() {
    this.notifyNewTodosQuerySubscription.unsubscribe();
    this.newTodosQuerySubscription.unsubscribe();
    this.oldTodosQuerySubscription.unsubscribe();
  }
}
