// tutorials/frontend/react-apollo-hooks/app-boilerplate/src/components/Auth/Login.js
import React from "react";
import { useAuth0 } from "./react-auth0-spa";

import { Button } from "react-bootstrap";

const Login = () => {
  const { loading, loginWithRedirect } = useAuth0();
  if (loading) {
    return <div>Loading...</div>;
  }
  return (
    <div className="overlay">
      <div className="overlay-content">
        <div className="overlay-heading">
          Welcome to the GraphQL tutorial app
        </div>
        <div className="overlay-message">Please login to continue</div>
        <div className="overlay-action">
          <Button
            id="qsLoginBtn"
            variant="primary"
            className="btn-margin loginBtn"
            onClick={() => {
              loginWithRedirect({});
            }}
          >
            Log In
          </Button>
        </div>
      </div>
    </div>
  );
};

export default Login;

// tutorials/frontend/svelte-apollo/app-boilerplate/src/components/Auth/Login.svelte
<script>
  import { getContext } from "svelte";
  import { AUTH_CONTEXT_KEY } from "./auth0-variables";
  import { Button } from "sveltestrap";
  const { loginWithRedirect } = getContext(AUTH_CONTEXT_KEY);
</script>

<div class="overlay">
  <div class="overlay-content">
    <div class="overlay-heading">Welcome to the GraphQL tutorial app</div>
    <div class="overlay-message">Please login to continue</div>
    <div class="overlay-action">
      <Button
        id="qsLoginBtn"
        color="primary"
        class="btn-margin loginBtn"
        on:click={() => {
          loginWithRedirect({});
        }}
      >
        Log In
      </Button>
    </div>
  </div>
</div>
