// tutorials/frontend/angular-apollo/app-boilerplate/src/app/Todo/TodoPrivateList.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'TodoPrivateList',
  templateUrl: './TodoPrivateList.template.html',
})

export class TodoPrivateList implements OnInit {
  filter = 'all';
  clearInProgress = false;
  todos = [
    {
      id: '1',
      title: 'This is private todo 1',
      is_completed: true,
      is_public: false
    },
    {
      id: '2',
      title: 'This is private todo 2',
      is_completed: false,
      is_public: false
    }
  ];
  filteredTodos: any;

  ngOnInit() {
    this.filteredTodos = this.todos;
  }

  filterResults($event) {
    this.filter = $event.filter;
    this.filteredTodos = this.todos;
    if (this.filter === 'active') {
      this.filteredTodos = this.todos.filter(todo => todo.is_completed !== true);
    } else if (this.filter === 'completed') {
      this.filteredTodos = this.todos.filter(todo => todo.is_completed === true);
    }
  }

  clearCompleted() { }
}

// tutorials/frontend/svelte-apollo/app-boilerplate/src/components/Todo/TodoPrivateList.svelte
<script>
  import TodoFilters from "./TodoFilters.svelte";
  import TodoItem from "./TodoItem.svelte";
  let currentFilter = "all";
  let todos = [
    {
      id: "1",
      title: "This is private todo 1",
      is_completed: true,
      is_public: false,
    },
    {
      id: "2",
      title: "This is private todo 2",
      is_completed: false,
      is_public: false,
    },
  ];

  function filterResults(filter) {
    currentFilter = filter;
  }
  function clearCompleted() {}

  function getFilteredTodos(todos, currentFilter) {
    if (currentFilter === "active") {
      return todos.filter((todo) => !todo.is_completed);
    } else if (currentFilter === "completed") {
      return todos.filter((todo) => todo.is_completed);
    }
    return todos;
  }

  $: filteredTodos = getFilteredTodos(todos, currentFilter);
</script>

<div>
  <div class="todoListWrapper">
    <ul>
      {#each filteredTodos as todo (todo.id)}
        <TodoItem {todo} />
      {/each}
    </ul>
  </div>
  <TodoFilters {todos} {currentFilter} {filterResults} {clearCompleted} />
</div>
