// tutorials/frontend/svelte-apollo/app-final/src/components/Todo/TodoInput.svelte
<script>
  import { gql } from "@apollo/client";
  import { mutation } from "svelte-apollo";
  import { GET_MY_TODOS } from "./queries";

  export let isPublic = false;
  let todoInput = "";

  const ADD_TODO = gql`
    mutation ($todo: String!, $isPublic: Boolean!) {
      insert_todos(objects: { title: $todo, is_public: $isPublic }) {
        affected_rows
        returning {
          id
          title
          created_at
          is_completed
        }
      }
    }
  `;

  const updateCache = (cache, { data }) => {
    // If this is for the public feed, do nothing
    if (isPublic) {
      return null;
    }

    // Fetch the todos from the cache
    const existingTodos = cache.readQuery({
      query: GET_MY_TODOS,
    });

    // Add the new todo to the cache
    const newTodo = data.insert_todos.returning[0];
    console.log(existingTodos, newTodo);
    cache.writeQuery({
      query: GET_MY_TODOS,
      data: { todos: [newTodo, ...existingTodos.todos] },
    });
  };

  const addTodoMutation = mutation(ADD_TODO);

  async function addTodo() {
    try {
      await addTodoMutation({
        variables: { todo: todoInput, isPublic },
        update: updateCache,
      });
      todoInput = "";
    } catch (error) {
      // TODO
    }
  }
</script>

<form class="formInput" on:submit|preventDefault={addTodo}>
  <input
    class="input"
    placeholder="What needs to be done?"
    bind:value={todoInput}
  />
  <i class="inputMarker fa fa-angle-right" />
</form>

// tutorials/frontend/react-apollo-hooks/app-final/src/components/Todo/TodoInput.js
import React, { useState } from "react";
import { useMutation } from "@apollo/react-hooks";
import gql from "graphql-tag";
import { GET_MY_TODOS } from "./TodoPrivateList";

const ADD_TODO = gql`
  mutation($todo: String!, $isPublic: Boolean!) {
    insert_todos(objects: { title: $todo, is_public: $isPublic }) {
      affected_rows
      returning {
        id
        title
        created_at
        is_completed
      }
    }
  }
`;

const TodoInput = ({ isPublic = false }) => {
  const [todoInput, setTodoInput] = useState("");

  const updateCache = (cache, { data }) => {
    // If this is for the public feed, do nothing
    if (isPublic) {
      return null;
    }

    // Fetch the todos from the cache
    const existingTodos = cache.readQuery({
      query: GET_MY_TODOS
    });

    // Add the new todo to the cache
    const newTodo = data.insert_todos.returning[0];
    cache.writeQuery({
      query: GET_MY_TODOS,
      data: { todos: [newTodo, ...existingTodos.todos] }
    });
  };

  const resetInput = () => {
    setTodoInput("");
  };

  const [addTodo] = useMutation(ADD_TODO, {
    update: updateCache,
    onCompleted: resetInput
  });

  return (
    <form
      className="formInput"
      onSubmit={e => {
        e.preventDefault();
        addTodo({ variables: { todo: todoInput, isPublic } });
      }}
    >
      <input
        className="input"
        value={todoInput}
        placeholder="What needs to be done?"
        onChange={e => setTodoInput(e.target.value)}
      />
      <i className="inputMarker fa fa-angle-right" />
    </form>
  );
};

export default TodoInput;
