// tutorials/frontend/rescript-react-apollo/app-final/src/components/Todo/TodoPrivateWrapper.js
import React from "react";

import TodoInput from "./TodoInput.bs";
import TodoPrivateList from "./TodoPrivateList";

const TodoPrivateWrapper = () => {
  return (
    <div className="todoWrapper">
      <div className="sectionHeader">Personal todos</div>

      <TodoInput isPublic={false} />
      <TodoPrivateList />
    </div>
  );
};

export default TodoPrivateWrapper;

// tutorials/frontend/vue3-apollo/app-boilerplate/src/components/TodoPrivateWrapper.vue
<template>
  <div class="todoWrapper">
    <TodoInput type="private" />
    <TodoPrivateList type="private" />
  </div>
</template>

<script>
import TodoInput from "../components/TodoInput.vue";
import TodoPrivateList from "../components/TodoPrivateList.vue";
export default {
  components: {
    TodoInput, TodoPrivateList
  }
}
</script>
