// tutorials/frontend/rescript-react-apollo/app-final/src/components/Todo/TodoPublicWrapper.js
import React from "react";

import TodoInput from "./TodoInput.bs";
import TodoPublicList from "./TodoPublicList";

const TodoPublicWrapper = () => {
  return (
    <div className="todoWrapper">
      <div className="sectionHeader">Public feed (realtime)</div>

      <TodoInput isPublic />
      <TodoPublicList />
    </div>
  );
};

export default TodoPublicWrapper;

// tutorials/frontend/vue3-apollo/app-boilerplate/src/components/TodoPublicWrapper.vue
<template>
  <div class="todoWrapper">
    <TodoInput type="public" />
    <TodoPublicList type="public" />
  </div>
</template>

<script>
import TodoInput from "../components/TodoInput.vue";
import TodoPublicList from "../components/TodoPublicList.vue";
export default {
  components: {
    TodoInput, TodoPublicList
  },
}
</script>
